### ISSUE TITLE
addon fails mozilla online sigining with version 41

### ISSUE THREAD

**Issue by buggyj** [buggyj/tiddlyclip#18]
from version 41 all addons need signing - 
we have some 'oncommand' defined by setting attibs that are flagged - can turn them into functions.

**Comment by zz0rk** [comment]
This is still (or again?) an issue on 45.3.0. I just tried to install the add-on. Firefox can't verify the signature.

**Comment by buggyj** [comment]
Hi @zz0rk 
see this thread - - I think it has the answer for you
https://groups.google.com/forum/#!searchin/tiddlywiki/tiddlyclip|sort:date/tiddlywiki/WnfHpKX9mqk/MPAKp7znBAAJ

**Comment by zz0rk** [comment]
Perfect; it worked. Any chance this could be added to the project documentation as an alternative installation method, if all fails? 
Cheers
