### ISSUE TITLE
Firefox Quantum

### ISSUE THREAD

**Issue by nibreh** [buggyj/tiddlyclip#34]
Hi

Are you working for an update to make tiddlyclip working with Firefox 57 Quantum ?

Thanks

**Comment by buggyj** [comment]
yes I have just go the plugin to the same level as with pre ff57. Are you using with TWClassic or TW5?

**Comment by nibreh** [comment]
In fact I use [TiddlySnip](https://github.com/JulianSchuette/tiddlysnip) with TWClassic, but I would like to use TW5 now. I tested TiddlyClip few month ago.

**Comment by gse-cc-git** [comment]
Hello,
Former user of tiddlyclip with my FF52 on linux, I cannot manage to get it work under FF Quantum.
When I right click on a page (after having docked tc to my wiki 5.1.15) I do not see any options besides "dock here", in the menu.

Is tiddlyclip 0.1.1 compatible[ with the tw plugin found here ?](http://tiddlyclip.tiddlyspot.com/)or have I missed something ?
Thanks for your help

**Comment by buggyj** [comment]
@gse-cc-git I am in the process of adding new functionality to tiddlyclip for firefox quantum. The new version will support all the old functionality. I will make a prerelease so that people can start to use the new version, but the new functionality may change.

**Comment by gse-cc-git** [comment]
Hello,
Thank you very much for your work !
I tried rapidly the prerelease bu t encountered the same issue.
Maybe it has somthing to do with my TiddlyWiki beeing accessed and edited from a remote webdav server ?
Sorry, I haven't the technical knowledge to judge. I can only make assumptions.
I'll try different options and let you know (like using TC with Quantum on a local file)

**Comment by buggyj** [comment]
Tiddlyclip works with remote and local files...
you can test you setup by going to http://tiddlyclip.tiddlyspot.com/
right click inside the page and click "dock here" (this enable tiddlyclip to work with the tiddlywiki).
right click again and you should see some tiddlyclip clipping options. 

tiddlyclip does have a lot of debug output so if this does not work we can look at what is failing...

**Comment by gse-cc-git** [comment]
Hello,
It works:

- like a charm with  [http://tiddlyclip.tiddlyspot.com/](http://tiddlyclip.tiddlyspot.com/)
- also with one of my TW on webdav
- but not with another...

Among the what distinguishes the two TWs: I installed many plugins on the "failing" TW and it is encrypted (passwd protected). Both have the 0.0.7-alpha Tw plugin

**Comment by buggyj** [comment]
tiddlyclip will not work with encripted tiddlywikis.

Tiddlyclip is only enabled with tiddlywikis, and it determines this when a page first loads. If the tiddlywiki is encrypted it cannot read the header (as it is encripted) as so the tiddlywiki is undockable. The testing upon page load is to stop malware automatically dock to the tiddlyclip plugin, so I cannot see away around this..

**Comment by gse-cc-git** [comment]
Thank you. I came to this conclusion... empirically.

**Comment by buggyj** [comment]
was fixed see #61
