### ISSUE TITLE
Keyboard shortcuts for the browser addon?

### ISSUE THREAD

**Issue by kriddly** [buggyj/tiddlyclip#68]
Hello :)
If I'm not mistaken, there are currently no keyboard shortcuts for the different functions of tiddlyclip browser addon (I'm on latest Mozilla Firefox, which has a menu for customizing addon shortcuts, but only for addons that have enabled those).

Clipping large quantities of "snips" and "snaps" is slowed down by having to navigate the context menu instead of using a pre-defined (or customizable) keyboard shortcut. Preferably entering the "snap selection" -mode would have a keyboard shortcut as well. Also preferably you could customize the keyboard shortcuts for any custom functions you add through the wiki-configuration, but I'm not sure whether that would be possible. Even the default ones would be a huge upgrade for this kind of workflow. I hope this is something that is possible to address.

Oh, and thank you for this amazing tool you've provided!
~K

**Comment by buggyj** [comment]
Hi @kriddly,
The operations of tiddlyclip are programmed by the tiddlywiki that the addon docks to, via the  TiddlyClipConfig tiddler. The user can change this tiddler and thus control the actions of addon (the items in the tiddlyclip context menu correspond to the tables in the  TiddlyClipConfig tiddller).  Unfortunately it is not possible to assign shortcut keys to the context menu items, so there is no way to attach keyboard short cuts. (There are no fixed functions in tiddlyclip all are user defined and appear in the context menu).

Below is a example of a TiddlyClipConfig from one of my tiddlywikis, 

all the best, BJ

![image](https://user-images.githubusercontent.com/2855795/131247009-473f9563-07ed-47d9-85b0-62f9cc98d25a.png)

**Comment by kriddly** [comment]
Thank you for clarifying. Now I realize that with arrow keys I can quite rapidly access the context menu options whenever I'm grabbing a lot of small bits of text across a page.
