### ISSUE TITLE
loading as a temporary extension?

### ISSUE THREAD

**Issue by kvgc** [buggyj/tiddlyclip#78]
Hi,
Version: 0.1.8
Thanks for making this tool! It's really cool! I am trying to install it as a temporary extension on firefox and develop it further, but loading the manifest.json does not quite seem to show all the features in the context menu. 

Installing the extension using the .xpi works fine though. I was wondering if there was a particular reason why loading the manifest.json directly only to about:debugging does not work?  
Thanks!

--
kvgc

**Comment by buggyj** [comment]
Hi @kvgc 
I am not aware of any issues with local loading, - actually I nearly always load TC this way as I am always testing new features. (There are lots of features in tiddlyclip that are not documented. )

**Comment by kvgc** [comment]
Hi @buggyj,
I think I figured what the issue here might be.

If I go to the recent release: https://github.com/buggyj/tiddlyclip/releases/tag/0.1.8 and download the source code from there. 

The manifest.json (attached below) seems to indicate that the version is for 0.0.8 and not for 0.1.8
```

{
	"manifest_version": 2,
	"web_accessible_resources": [
		"content/resources/css/*.css"
	],
	"background" : {
		"page" : "content/background.html"
	},
	"content_scripts" : [ {
		"js" : [
			"content/util/logsimple.js"	,		
			"content/contentScript.js"
		],
      "matches" : [
        "http://*/*",
        "file:///*",
        "https://*/*"
      ],
		"run_at" : "document_start"
	} ],
	"description" : "A context menu extension for tiddlywiki",
	"icons" : {
		"16" : "skin/icon16.png",
		"48" : "skin/icon-48.png"
	},
	"name" : "tiddlyclip",
	"permissions" : [
		"tabs", "<all_urls>",
		"contextMenus",
		"notifications"
	],

	"version" : "0.0.8"
}

```
Could you offer some clarification on this?
Thanks!

**Comment by buggyj** [comment]
I can confirm that the zip contains an old version

**Comment by buggyj** [comment]
Unfortunately I cannot find away to change these files, I guess they are not very useful in general.
